name: Deploy Infrastructure

on:
  push:
    branches:
      - master

jobs:
  terraform-plan:
    name: Blog Deploy Plan
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout Repo"
        uses: actions/checkout@v2

      # - uses: webfactory/ssh-agent@v0.5.4
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Build AWS Credentials"
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: "Setup Terraform CLI"
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
        
      - name: Terraform Plan
        id: plan
        run: terraform plan
